// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-MjePbAuoKwR2LDWfZ3NQkSvx8JF1ut4',
    appId: '1:384956286126:web:1c0d824ee3be437d67993f',
    messagingSenderId: '384956286126',
    projectId: 'blizz-app',
    authDomain: 'blizz-app.firebaseapp.com',
    storageBucket: 'blizz-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGNHEA7_haVHPsurkizLKJVhOYaIJduaU',
    appId: '1:384956286126:android:ca0e06016e039a8467993f',
    messagingSenderId: '384956286126',
    projectId: 'blizz-app',
    storageBucket: 'blizz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtecKCIPAyZqUGs8hVyck4LjCUiPpy7EU',
    appId: '1:384956286126:ios:081eda2ba81a70db67993f',
    messagingSenderId: '384956286126',
    projectId: 'blizz-app',
    storageBucket: 'blizz-app.appspot.com',
    iosClientId: '384956286126-503b4lgulce69skpu9o9g1am06tki5mj.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
